config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, UserResetPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', UserCreateView.email_verification, name='email-confirm'),
    path('reset-password/', UserResetPasswordView.as_view(template_name='users/user_reset_password.html'),
         name='reset-password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта', help_text='Введите адрес электронной почты')
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name='Телефон', help_text='Введите номер телефона')
    avatar = models.ImageField(upload_to='users/avatars', **NULLABLE, verbose_name='Аватар',
                               help_text='Загрузите свой аватар')
    country = models.CharField(max_length=50, **NULLABLE, verbose_name='Страна', help_text='Введите название страны')

    token = models.CharField(max_length=100, **NULLABLE, verbose_name='Токен')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

users/views.py
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, FormView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейти по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)

    @staticmethod
    def email_verification(request, token):
        user = get_object_or_404(User, token=token)
        user.is_active = True
        user.save()
        return redirect(reverse('users:login'))


class UserResetPasswordView(FormView):
    model = User
    form_class = PasswordResetForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        random_password = secrets.token_hex(16)
        for user in form.get_users(email):
            user.set_password(random_password)
            user.save()
        send_mail(
            subject='Password reset',
            message=f'Hello your password {random_password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[email],
        )

        return super().form_valid(form)

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    Log in
{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                <div class="row row-cols-1 row-cols-sm-2 row-cols g-2">
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-outline-success">
                                    Log in
                                </button>
                                <a class="btn btn-outline-info" role="button" aria-disabled="true"
                                href="{% url 'users:reset-password' %}">Recover password</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    Registration
{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                <div class="row row-cols-1 row-cols-sm-2 row-cols g-2">
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-outline-success">
                                    Registration
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/user_reset_password.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    Reset password
{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <form method="post">
                <div class="row row-cols-1 row-cols-sm-2 row-cols g-2">
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-warning">
                                    Reset password
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}