catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ContactView, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = CatalogConfig.name
urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('catalog/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_info'),
    path('catalog/create/', ProductCreateView.as_view(), name='create_product'),
    path('catalog/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('catalog/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('contact/', ContactView.as_view(), name='contact_info'),
    path('blog', BlogListView.as_view(), name='blog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_info'),
    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='update_blog'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, UserResetPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', UserCreateView.email_verification, name='email-confirm'),
    path('reset-password/', UserResetPasswordView.as_view(template_name='users/user_reset_password.html'),
         name='reset-password'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    id = models.CharField(primary_key=True, max_length=100, verbose_name='Номер категории')
    name = models.CharField(max_length=100, verbose_name='Категория продукта')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ['id', ]


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Товар')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    photo = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория товара')
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ['category', 'pk', ]
        permissions = [
            ('cancel_is_published', 'cancel is_published'),
            ('edit_description', 'edit description'),
            ('edit_category', 'edit category'),
        ]

class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='Короткая метка')
    body = models.TextField(**NULLABLE, verbose_name='Содержимое')
    image = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    status = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Блог продукта')

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ['-created_at', 'product', ]

    def __str__(self):
        return self.title


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number_version = models.FloatField(verbose_name='Номер версии')
    name_version = models.CharField(max_length=100, verbose_name='Название версии')
    is_active_version = models.BooleanField(default=True, verbose_name='Активная версия')

    def __str__(self):
        return f'{self.product}, {self.name_version} - {self.number_version}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
import re

from django import forms
from django.forms import BooleanField

from catalog.models import Product, Version

exclude_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'photo', 'category', 'price']

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for data_word in exclude_words:
            if re.search(data_word, cleaned_data.lower(), flags=re.S) is not None:
                raise forms.ValidationError(f'Название товара содержит запрещенное слово - {data_word}')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for data_word in exclude_words:
            if re.search(data_word, cleaned_data.lower(), flags=re.S) is not None:
                raise forms.ValidationError(f'Описание товара содержит запрещенное слово - {data_word}')
        return cleaned_data


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('is_published', 'category', 'description')


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_number_version(self):
        cleaned_data = self.cleaned_data['number_version']
        if cleaned_data < 0:
            raise forms.ValidationError('Номер версии не может быть меньше 0')
        return cleaned_data

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from catalog.forms import ProductForm, ProductModeratorForm, VersionForm
from catalog.models import Product, Blog, Version
from config.services import get_products_from_cache


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = get_products_from_cache(self.model)
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Main page"
        context["description"] = "Auto parts"
        for product in context.get("object_list"):
            product.version = product.version_set.filter(is_active_version=True).first()
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Page product"
        version = self.object.version_set.filter(is_active_version=True).first()
        context["version"] = version
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:index")
    extra_context = {"title": "Create product"}

    def form_valid(self, form):
        product = form.save(commit=False)
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse("catalog:product_info", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update product"
        if not self.request.user.groups.filter(name="moderator").exists():
            VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
            if self.request.method == "POST":
                context["formset"] = VersionFormset(self.request.POST, instance=self.object)
            else:
                context["formset"] = VersionFormset(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context.get("formset")

        if form.is_valid():
            self.object = form.save()
            if formset and formset.is_valid():
                formset.instance = self.object
                formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (
                user.has_perm("catalog.cancel_is_published")
                and user.has_perm("catalog.edit_description")
                and user.has_perm("catalog.edit_category")
        ):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:index")
    extra_context = {"title": "Delete product"}


class ContactView(TemplateView):
    template_name = "catalog/contact_info.html"

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"Имя: {name}, Номер телефона: {phone}, Сообщение: {message}")
        return render(request, self.template_name)


class BlogListView(ListView):
    model = Blog
    extra_context = {"title": "Blog"}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(status=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog
    extra_context = {"title": "Page blog"}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ["title", "image", "status", "product", ]
    success_url = reverse_lazy("catalog:blog")
    extra_context = {"title": "Create blog"}

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save(commit=False)
            blog.slug = slugify(blog.title)
            blog.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ["title", "image", "status", "product", ]
    extra_context = {"title": "Update blog"}

    def get_success_url(self):
        return reverse("catalog:blog_info", args=[self.object.product.pk])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("catalog:blog")
    extra_context = {"title": "Delete blog"}

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    Delete page
{% endblock %}

{% block title %}
    <h2 class="display-4 fw-bold">{{ title }}</h2>
{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <p>Delete blog: {{ object.title }}?</p>
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn--sm btn-danger">Delete</button>
                                <a class="btn btn--sm btn-outline-secondary"
                                   href="{% url 'catalog:blog_info' object.pk %}" role="button">Cancel</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    {{ object.slug }}
{% endblock %}

{% block title %}
    <h2 class="display-5 fw-bold">{{ title }}</h2>
{% endblock %}

{% block content %}
    <main>
        <div class="album py-5 bg-body-tertiary">
            <div class="container-fluid">
                <div class="card">
                    <div class="col">
                        <div class="card shadow-sm m-lg-3">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Data of creation: {{ object.created_at }}</li>
                                <li class="list-group-item">Data of published: {{ object.status }}</li>
                                <li class="list-group-item">Data of count view: {{ object.view_count }}</li>
                            </ul>
                            <img class="align-self-start" src="{{ object.photo | mymedia }}"
                                 style="height: 200px;width: auto;">
                            <div class="card-body">
                                <div class="card-header py-2">
                                    <h5 class="my-1 fw-normal">{{ object.title }}
                                        (Product: {{ object.product }})</h5>
                                </div>
                                <div class="card-header py-2">
                                    {% if object.body %}
                                        <p class="text-start m-3">{{ object.body }}</p>
                                    {% else %}
                                        Not body
                                    {% endif %}
                                </div>
                                <div class="btn-group m-sm-2">
                                    <a class="btn btn--sm btn-outline-secondary"
                                       href="{% url 'catalog:blog' %}"
                                       role="button">Main
                                    </a>
                                    <a class="btn btn--sm btn-outline-secondary"
                                       href="{% url 'catalog:update_blog' object.id %}"
                                       role="button">Update
                                    </a>
                                    <a class="btn btn--sm btn-outline-secondary"
                                       href="{% url 'catalog:delete_blog' object.id %}"
                                       role="button">Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    {% if object %}
        Update page
    {% else %}
        Create page
    {% endif %}
{% endblock %}

{% block title %}
    <h2 class="display-4 fw-bold">{{ title }}</h2>
{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-outline-success">
                                    {% if object %}
                                        Update
                                    {% else %}
                                        Create
                                    {% endif %}
                                </button>
                                {% if object %}
                                    <a class="btn btn--sm btn-outline-secondary"
                                   href="{% url 'catalog:blog_info' object.pk %}" role="button">Cancel</a>
                                {% else %}
                                    <a class="btn btn--sm btn-outline-secondary"
                                   href="{% url 'catalog:blog' %}" role="button">Cancel</a>
                                {% endif %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    Blog page
{% endblock %}

{% block title %}
    <h2 class="display-5 fw-bold">{{ title }}</h2>
{% endblock %}

{% block content %}
    <main>
        <div class="album py-5 bg-body-tertiary">
            <div class="container-fluid">
                <a class="btn btn-primary mb-3"
                   href="{% url 'catalog:create_blog' %}" role="button">Create blog
                </a>
                <div class="card">
                    {% for object in object_list %}
                        <div class="col">
                            <div class="card shadow-sm m-lg-3">
                                <img class="align-self-start" src="{{ object.photo | mymedia }}"
                                     style="height: 100px;width: auto;">
                                <div class="card-body">
                                    <div class="card-header py-2">
                                        <h5 class="my-1 fw-normal">{{ object.title }}
                                            (Product: {{ object.product }})</h5>
                                    </div>
                                    <div class="card-header py-2">
                                        {% if object.body %}
                                            <p class="text-start m-3">{{ object.body|truncatewords:15 }}</p>
                                        {% else %}
                                            Not body
                                        {% endif %}
                                    </div>
                                    <div class="btn-group m-sm-2">
                                        <a class="btn btn--sm btn-outline-secondary"
                                           href="{% url 'catalog:blog_info' object.id %}"
                                           role="button">View
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

catalog/templates/catalog/contact_info.html
{% extends 'catalog/contact_base.html' %}

{% block contact %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Contact</h1>
    </div>
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Контактный телефон" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    Delete page
{% endblock %}

{% block title %}
    <h2 class="display-4 fw-bold">{{ title }}</h2>
{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <p>Удалить объект: {{ object.name }}?</p>
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn--sm btn-danger">Delete</button>
                                <a class="btn btn--sm btn-outline-secondary"
                                   href="{% url 'catalog:index' %}" role="button">Cancel</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    {{ object.name }}
{% endblock %}

{% block title %}
    <h2 class="display-4 fw-bold">{{ title }}</h2>
{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container-fluid">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ object.photo | mymedia }}"
                             style="height: 300px;width: auto;">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.name }}</h5>
                            <p class="card-text">{{ object.description }}</p>
                            <h4 class="card-title pricing-card-title">Price: {{ object.price }}</h4>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Category product: {{ object.category }}</li>
                                <li class="list-group-item">Date of creation: {{ object.created_at }}</li>
                                <li class="list-group-item">Date of update: {{ object.updated_at }}</li>
                                <li class="list-group-item">Name version: {{ version.name_version }}</li>
                                <li class="list-group-item">Number version: {{ version.number_version }}</li>
                            </ul>
                            <div class="btn-group">
                                <a class="btn btn--sm btn-outline-secondary"
                                   href="{% url 'catalog:index' %}" role="button">Main
                                </a>
                                {% if perms.catalog.cancel_is_published and perms.catalog.edit_description and perms.catalog.edit_category or user == product.owner %}
                                <a class="btn btn--sm btn-outline-secondary"
                                   href="{% url 'catalog:update_product' object.id %}" role="button">Update</a>
                                {% endif %}
                                {% if user.is_superuser%}
                                <a class="btn btn--sm btn-outline-secondary"
                                   href="{% url 'catalog:delete_product' object.id %}" role="button">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block title_page %}
    Product page
{% endblock %}


{% block title %}
    <h2 class="display-5 fw-bold">{{ title }}</h2>
    <h3 class="fw-normal text-muted mb-3">{{ description }}</h3>
{% endblock %}

{% block content %}
    <main>
        <div class="album py-5 bg-body-tertiary">
            <div class="container-fluid">
                <a class="btn btn-primary mb-3"
                   href="{% url 'catalog:create_product' %}" role="button">Create product
                </a>
                <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 g-4">
                    {% for object in object_list %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <img class="img-fluid" src="{{ object.photo | mymedia }}"
                                     style="height: 300px;width: auto;">
                                <div class="card-body">
                                    <div class="card-header py-2">
                                        <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                                    </div>
                                    <div class="card-header py-2">
                                        <h4 class="card-title pricing-card-title">Price: {{ object.price }}</h4>
                                        <p class="text-start m-3">{{ object.description|truncatewords:100 }}</p>
                                    </div>
                                    <div class="card-header py-2">
                                        <p class="card-text">Name version: {{ object.version.name_version }}</p>
                                        <p class="card-text">Number version: {{ object.version.number_version }}</p>
                                    </div>
                                    <div class="btn-group m-sm-2">
                                        <a class="btn btn--sm btn-outline-secondary"
                                           href="{% url 'catalog:product_info' object.id %}"
                                           role="button">View
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}